#############################################################################
# Makefile for building: test_usbpv_lib_s
# Generated by qmake (3.1) (Qt 5.15.3)
# Project:  ./usbpv_lib_s_test.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile ./usbpv_lib_s_test.pro -spec linux-g++
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options
### setup your own toolchain here ####
# e.g.
# TOOLCHAIN_PREFIX = /home/vm/work/aarch64-ca53-linux-gnueabihf-8.4/bin/aarch64-ca53-linux-gnu-
TOOLCHAIN_PREFIX = 
CC            = $(TOOLCHAIN_PREFIX)gcc
CXX           = $(TOOLCHAIN_PREFIX)g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I./libusb-1.0.23 -I./libusb-1.0.23/libusb
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = test_usbpv_lib_s1.0.0
LINK          = $(TOOLCHAIN_PREFIX)g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -ludev -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./obj

####### Files

SOURCES       = ./usbpv_s.cpp \
		./usbpv_util.cpp \
		./test_usbpv_s.cpp \
		./libusb-1.0.23/libusb/core.c \
		./libusb-1.0.23/libusb/descriptor.c \
		./libusb-1.0.23/libusb/hotplug.c \
		./libusb-1.0.23/libusb/io.c \
		./libusb-1.0.23/libusb/strerror.c \
		./libusb-1.0.23/libusb/sync.c \
		./libusb-1.0.23/libusb/os/poll_posix.c \
		./libusb-1.0.23/libusb/os/threads_posix.c \
		./libusb-1.0.23/libusb/os/linux_usbfs.c \
		./libusb-1.0.23/libusb/os/linux_udev.c 
OBJECTS       = $(OBJECTS_DIR)/usbpv_s.o \
		$(OBJECTS_DIR)/usbpv_util.o \
		$(OBJECTS_DIR)/test_usbpv_s.o \
		$(OBJECTS_DIR)/core.o \
		$(OBJECTS_DIR)/descriptor.o \
		$(OBJECTS_DIR)/hotplug.o \
		$(OBJECTS_DIR)/io.o \
		$(OBJECTS_DIR)/strerror.o \
		$(OBJECTS_DIR)/sync.o \
		$(OBJECTS_DIR)/poll_posix.o \
		$(OBJECTS_DIR)/threads_posix.o \
		$(OBJECTS_DIR)/linux_usbfs.o \
		$(OBJECTS_DIR)/linux_udev.o

QMAKE_TARGET  = $(OBJECTS_DIR)/test_usbpv_lib_s
DESTDIR       = 
TARGET        = $(OBJECTS_DIR)/test_usbpv_lib_s


first: all
####### Build rules

test_usbpv_lib_s:$(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

obj_dir:
	$(MKDIR) $(OBJECTS_DIR)

all: obj_dir test_usbpv_lib_s

clean: 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) *~ core *.core

####### Compile

$(OBJECTS_DIR)/usbpv_s.o: ./usbpv_s.cpp ./usbpv_s.h \
		./libusb-1.0.23/libusb/libusb.h \
		./init_data.txt
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/usbpv_s.o ./usbpv_s.cpp

$(OBJECTS_DIR)/usbpv_util.o: ./usbpv_util.cpp ./usbpv_s.h \
		./libusb-1.0.23/libusb/libusb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/usbpv_util.o ./usbpv_util.cpp

$(OBJECTS_DIR)/test_usbpv_s.o: ./test_usbpv_s.cpp ./usbpv_s.h \
		./libusb-1.0.23/libusb/libusb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/test_usbpv_s.o ./test_usbpv_s.cpp

$(OBJECTS_DIR)/core.o: ./libusb-1.0.23/libusb/core.c ./config.h \
		./libusb-1.0.23/libusb/libusbi.h \
		./libusb-1.0.23/libusb/libusb.h \
		./libusb-1.0.23/libusb/version.h \
		./libusb-1.0.23/libusb/version_nano.h \
		./libusb-1.0.23/libusb/os/threads_posix.h \
		./libusb-1.0.23/libusb/os/threads_windows.h \
		./libusb-1.0.23/libusb/os/poll_posix.h \
		./libusb-1.0.23/libusb/os/poll_windows.h \
		./libusb-1.0.23/libusb/hotplug.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/core.o ./libusb-1.0.23/libusb/core.c

$(OBJECTS_DIR)/descriptor.o: ./libusb-1.0.23/libusb/descriptor.c ./config.h \
		./libusb-1.0.23/libusb/libusbi.h \
		./libusb-1.0.23/libusb/libusb.h \
		./libusb-1.0.23/libusb/version.h \
		./libusb-1.0.23/libusb/version_nano.h \
		./libusb-1.0.23/libusb/os/threads_posix.h \
		./libusb-1.0.23/libusb/os/threads_windows.h \
		./libusb-1.0.23/libusb/os/poll_posix.h \
		./libusb-1.0.23/libusb/os/poll_windows.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/descriptor.o ./libusb-1.0.23/libusb/descriptor.c

$(OBJECTS_DIR)/hotplug.o: ./libusb-1.0.23/libusb/hotplug.c ./config.h \
		./libusb-1.0.23/libusb/libusbi.h \
		./libusb-1.0.23/libusb/libusb.h \
		./libusb-1.0.23/libusb/version.h \
		./libusb-1.0.23/libusb/version_nano.h \
		./libusb-1.0.23/libusb/os/threads_posix.h \
		./libusb-1.0.23/libusb/os/threads_windows.h \
		./libusb-1.0.23/libusb/os/poll_posix.h \
		./libusb-1.0.23/libusb/os/poll_windows.h \
		./libusb-1.0.23/libusb/hotplug.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/hotplug.o ./libusb-1.0.23/libusb/hotplug.c

$(OBJECTS_DIR)/io.o: ./libusb-1.0.23/libusb/io.c ./config.h \
		./libusb-1.0.23/libusb/libusbi.h \
		./libusb-1.0.23/libusb/libusb.h \
		./libusb-1.0.23/libusb/version.h \
		./libusb-1.0.23/libusb/version_nano.h \
		./libusb-1.0.23/libusb/os/threads_posix.h \
		./libusb-1.0.23/libusb/os/threads_windows.h \
		./libusb-1.0.23/libusb/os/poll_posix.h \
		./libusb-1.0.23/libusb/os/poll_windows.h \
		./libusb-1.0.23/libusb/hotplug.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/io.o ./libusb-1.0.23/libusb/io.c

$(OBJECTS_DIR)/strerror.o: ./libusb-1.0.23/libusb/strerror.c ./config.h \
		./libusb-1.0.23/libusb/libusbi.h \
		./libusb-1.0.23/libusb/libusb.h \
		./libusb-1.0.23/libusb/version.h \
		./libusb-1.0.23/libusb/version_nano.h \
		./libusb-1.0.23/libusb/os/threads_posix.h \
		./libusb-1.0.23/libusb/os/threads_windows.h \
		./libusb-1.0.23/libusb/os/poll_posix.h \
		./libusb-1.0.23/libusb/os/poll_windows.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/strerror.o ./libusb-1.0.23/libusb/strerror.c

$(OBJECTS_DIR)/sync.o: ./libusb-1.0.23/libusb/sync.c ./config.h \
		./libusb-1.0.23/libusb/libusbi.h \
		./libusb-1.0.23/libusb/libusb.h \
		./libusb-1.0.23/libusb/version.h \
		./libusb-1.0.23/libusb/version_nano.h \
		./libusb-1.0.23/libusb/os/threads_posix.h \
		./libusb-1.0.23/libusb/os/threads_windows.h \
		./libusb-1.0.23/libusb/os/poll_posix.h \
		./libusb-1.0.23/libusb/os/poll_windows.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/sync.o ./libusb-1.0.23/libusb/sync.c

$(OBJECTS_DIR)/poll_posix.o: ./libusb-1.0.23/libusb/os/poll_posix.c ./config.h \
		./libusb-1.0.23/libusb/libusbi.h \
		./libusb-1.0.23/libusb/libusb.h \
		./libusb-1.0.23/libusb/version.h \
		./libusb-1.0.23/libusb/version_nano.h \
		./libusb-1.0.23/libusb/os/threads_posix.h \
		./libusb-1.0.23/libusb/os/threads_windows.h \
		./libusb-1.0.23/libusb/os/poll_posix.h \
		./libusb-1.0.23/libusb/os/poll_windows.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/poll_posix.o ./libusb-1.0.23/libusb/os/poll_posix.c

$(OBJECTS_DIR)/threads_posix.o: ./libusb-1.0.23/libusb/os/threads_posix.c ./config.h \
		./libusb-1.0.23/libusb/os/threads_posix.h \
		./libusb-1.0.23/libusb/libusbi.h \
		./libusb-1.0.23/libusb/libusb.h \
		./libusb-1.0.23/libusb/version.h \
		./libusb-1.0.23/libusb/version_nano.h \
		./libusb-1.0.23/libusb/os/threads_windows.h \
		./libusb-1.0.23/libusb/os/poll_posix.h \
		./libusb-1.0.23/libusb/os/poll_windows.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/threads_posix.o ./libusb-1.0.23/libusb/os/threads_posix.c

$(OBJECTS_DIR)/linux_usbfs.o: ./libusb-1.0.23/libusb/os/linux_usbfs.c ./config.h \
		./libusb-1.0.23/libusb/libusbi.h \
		./libusb-1.0.23/libusb/libusb.h \
		./libusb-1.0.23/libusb/version.h \
		./libusb-1.0.23/libusb/version_nano.h \
		./libusb-1.0.23/libusb/os/threads_posix.h \
		./libusb-1.0.23/libusb/os/threads_windows.h \
		./libusb-1.0.23/libusb/os/poll_posix.h \
		./libusb-1.0.23/libusb/os/poll_windows.h \
		./libusb-1.0.23/libusb/os/linux_usbfs.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/linux_usbfs.o ./libusb-1.0.23/libusb/os/linux_usbfs.c

$(OBJECTS_DIR)/linux_udev.o: ./libusb-1.0.23/libusb/os/linux_udev.c ./config.h \
		./libusb-1.0.23/libusb/libusbi.h \
		./libusb-1.0.23/libusb/libusb.h \
		./libusb-1.0.23/libusb/version.h \
		./libusb-1.0.23/libusb/version_nano.h \
		./libusb-1.0.23/libusb/os/threads_posix.h \
		./libusb-1.0.23/libusb/os/threads_windows.h \
		./libusb-1.0.23/libusb/os/poll_posix.h \
		./libusb-1.0.23/libusb/os/poll_windows.h \
		./libusb-1.0.23/libusb/os/linux_usbfs.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/linux_udev.o ./libusb-1.0.23/libusb/os/linux_udev.c


